### ISSUE TITLE
Failed downloading retinaface_r50_v1

### ISSUE THREAD

**Issue by nhanhttrong** [michaildoukas/headGAN#4]
Hi i get this error 
![image](https://github.com/michaildoukas/headGAN/assets/139416619/873f265b-35c4-42b0-b9cc-55e8527d7b6e)
Can you help me solve it?
Thank you very much

**Comment by michaildoukas** [comment]
Hi,

The link to retinaface_r50_v1 weights appears to be broken. I added a new download link. Please pull the last changes, and run `python scripts/download_files.py` again.
